name: set-up

on: push

env:
 BUILD: Debug

jobs:
 Build-Test-Upload:
  runs-on: windows-latest
  defaults:
   run:
    working-directory: ${{github.workspace}}/main/
  steps:
  - uses: actions/checkout@v2
  - name: Download GoogleTest
    run: git clone https://github.com/google/googletest.git


