name: set-up

on: push

env:
 BUILD: Debug

jobs:
 Build-Test-Upload:
  runs-on: windows-latest
  steps:
  - uses: actions/checkout@v2
  - name: Download GoogleTest
    run: git clone https://github.com/google/googletest.git
    
  - name: CMake
    run: cmake -B ${{github.workspace}}/LAB1/build -DCMAKE_BUILD_TYPE=${{env.BUILD}}


